### PR TITLE
1.0.3

### PR DESCRIPTION
**Pull request by vertical-blank**

### CODE REVIEW

**Comment by vatsalmevada** [comment]
Thanks, @vertical-blank for cutting a new release. By when the new version will be available on maven central?

**Comment by vertical-blank** [comment]
@vatsalmevada 
I've staged new version, but I missed to presss "release" button...
I've done it about 5 hours ago, and now that is available on maven central.

**Comment by vatsalmevada** [comment]
@vertical-blank , still can not see 1.0.3 on maven. https://mvnrepository.com/artifact/com.github.vertical-blank/sql-formatter 

Am I looking at the right location?

**Comment by vertical-blank** [comment]
@vatsalmevada 
mvnrepository.com takes more time than [Sonatype](https://search.maven.org/search?q=g:%22com.github.vertical-blank%22%20AND%20a:%22sql-formatter%22) to reflect new release.

Actual URL of artifact being grabbed by maven(or sbt, gradle etc...) is this.
`https://repo1.maven.org/maven2/com/github/vertical-blank/sql-formatter/1.0.3/`

And, this script works for me.

```bash
groovy ./test.groovy
```

```groovy
@Grab('com.github.vertical-blank:sql-formatter:1.0.3')

import com.github.vertical_blank.sqlformatter.SqlFormatter
println SqlFormatter.format("SELECT * FROM table1")
```

**Comment by vatsalmevada** [comment]
@vertical-blank got it. Thanks!

**Pull request merged**
